### ISSUE TITLE
bit-panel should add show/hide class

### ISSUE THREAD

**Issue by daffl** [bitovi-components/bit-tabs#12]
Currently we just remove the content. This does not work when you set `display: block;` for `bit-panel`.

**Comment by daffl** [comment]
You could set

``` css
bit-panel:empty {
  display: none;
}
```

But I think a class would still be useful.
