### ISSUE TITLE
First tab doesn’t show up as selected by default

### ISSUE THREAD

**Issue by chasenlehara** [bitovi-components/bit-tabs#24]
I believe this is a regression. When a component with `bit-tabs` is first loaded, none of the tabs are selected, even though the correct content is shown.

Example from the DoneJS quick start guide:
!["Screenshot showing the bug"](https://donejs.com/static/img/donejs-electron-app.png)

**Comment by matthewp** [comment]
I noticed this but thought it was a change in bootstrap's css.

**Comment by matthewp** [comment]
The bootstrap CSS is:

```css
.nav > li > a:hover,
.nav > li > a:focus {
  text-decoration: none;
  background-color: #eeeeee;
}
```

So that's why the tab doesn't appear selected. Of course we could choose to override these styles ourselves if we like.
